// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRAVdYSHAvUQ2PmPJ2e0jNC_tnhTIAg70',
    appId: '1:32691788961:web:2ef20ee6afd413306664e0',
    messagingSenderId: '32691788961',
    projectId: 'eatzy-cd2cc',
    authDomain: 'eatzy-cd2cc.firebaseapp.com',
    storageBucket: 'eatzy-cd2cc.firebasestorage.app',
    measurementId: 'G-B384G8ZV3Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5QTkmLUFivH8NXuMZzPyenKN7XddVKWs',
    appId: '1:32691788961:android:881e4a40ff94750e6664e0',
    messagingSenderId: '32691788961',
    projectId: 'eatzy-cd2cc',
    storageBucket: 'eatzy-cd2cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUYJbYoT8scEXZAio4drDXyKXncXVaLjM',
    appId: '1:32691788961:ios:e718f638c071d6e56664e0',
    messagingSenderId: '32691788961',
    projectId: 'eatzy-cd2cc',
    storageBucket: 'eatzy-cd2cc.firebasestorage.app',
    iosBundleId: 'com.example.eatzy',
  );
}
